name: Build and Test

on:
  push:
    branches-ignore:
      - main
    tags:
      - "*"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GAR_LOCATION: ${{ secrets.GCP_LOCATION }} # TODO: update region of the Artifact Registry
  REPOSITORY: ${{ secrets.REPOSITORY_NAME }} # TODO: update to Artifact Registry docker repository
  IMAGE: ${{ secrets.IMAGE_NAME }}

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: GCP

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Create .env.test.local ファイル
      - name: Create .env.test.local file
        run: |
          cat << EOF > shanari-shanari-fe/.env.test.local
          ENVIRONMENT=${{ secrets.ENV_TEST }}
          AD_PUBLISHER_ID=${{ secrets.AD_PUBLISHER_ID }}
          AD_SLOT=${{ secrets.AD_SLOT }}
          TOPCUT_TOP=8
          TOPCUT_DETAIL=10
          PINO_LOG_LEVEL=info
          EOF

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Test
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
      - name: npm-install
        run: npm install --save-dev
        working-directory: ./shanari-shanari-fe
      - name: Jest Test
        run: npm run test
        working-directory: ./shanari-shanari-fe
